### ISSUE TITLE
ArtNetSocket DontFragment throwing Operation not supported

### ISSUE THREAD

**Issue by alfie1706** [HakanL/Haukcode.ArtNet#4]
Hi,

When trying to use DontFragment on an ArtNetSocket Object it is Throwing Error:

```c#
[8/29/2023 10:20:12 PM] System.Net.Sockets.SocketException (45): Operation not supported
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, Boolean disconnectOnFailure, String callerName)
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketOptionErrorAndThrowException(SocketError error, String callerName)
``` 

Code snippet:

```c#
private ArtNetSocket artNetClient;

[.....]

this.artNetClient = new ArtNetSocket();
this.artNetClient.EnableBroadcast = true;
this.artNetClient.SetSocketOption(System.Net.Sockets.SocketOptionLevel.Socket, System.Net.Sockets.SocketOptionName.ReuseAddress, true);
this.artNetClient.Open(ipAddress, IPAddress.Parse("255.255.255.0"));
this.artNetClient.Ttl = 128;
try
{
       this.artNetClient.DontFragment = true;
}
catch(Exception e)
{
        cout(e.ToString());
}
``` 

Is there anything I can do to fix this? Any help appreciated!

**Comment by HakanL** [comment]
I think options like that has to be set before you open the socket, see if that works.

**Comment by alfie1706** [comment]
No luck. Throws the same error regardless of where in the options I try and set it.

**Comment by HakanL** [comment]
This code works for me (Windows .NET 7):
![image](https://github.com/HakanL/Haukcode.ArtNet/assets/407941/4a63d0dd-1b4f-44ea-9913-0a5a07a66af4)

However, it also works if I put it after the Open. What kind of network adapter are you binding it to, what's the IP?

**Comment by HakanL** [comment]
What's your OS? Could it be related to this? https://github.com/dotnet/runtime/issues/76422

**Comment by alfie1706** [comment]
Ah yes. I'm running on MacOS at present, so that is likely the issue, unfortunately. But to answer your prior question I am running on a 2.0.0.x IP Range and its over ethernet, though I doubt that would make much difference.

I'll give the same code a go in my windows environment and let you know if it yields success.

**Comment by HakanL** [comment]
I see. I do wonder if you actually need this option set, ArtNet packets are like <700 bytes and most MTU is quite a bit larger than that.

**Comment by alfie1706** [comment]
I'm currently troubleshooting an issue in my use case where I am sending very specific packets to an ArtNet hardware device, a [Luminode](https://www.luminex.be/products/luminode/luminode-1/). The only difference I can see between a working packet that I am able to generate through traditional lighting controllers and mine is fragmentation being set.

Have tested on Windows and whilst I haven't tested whether the packet works with the hardware, it compiles at least so I imagine that the issue is limited to MacOS as you described.

**Comment by HakanL** [comment]
Strange that DontFragment would make a difference, in theory it should only be applied on routers or gateways when the NIC has a smaller MTU. Hopefully you'll figure it out, Wireshark is your friend.
