### ISSUE TITLE
OpCodes are read and defined incorrectly.

### ISSUE THREAD

**Issue by JoeSchulte** [HakanL/Haukcode.ArtNet#7]
From the spec: **The OpCode defines the class of data following ArtPoll within this UDP packet. Transmitted low byte first.**
Instead of reading is as OpCode = (ArtNetOpCodes)data.ReadNetwork16();  It should always read the low byte and then the high byte and combine them together instead of relying on the byte order defined by the network.
These codes should be in the range of 0x2000 to 0x9b00. Currently it doesn't support codes like OpVideoSetup that is defined as 0xa010.

**Comment by HakanL** [comment]
I think you're right, I agree that it seems wrong the way it's currently in the code. Let me see if we can rewrite this without causing issues.

**Comment by HakanL** [comment]
I've changed the OpCodes enum to the proper list from the specification, added the missing OpCodes, and refactored the readers/writers to be explicit in which order the bytes are read/written. Thanks for reporting this! Available in NuGet package 1.3.12 and later.

**Comment by JoeSchulte** [comment]
Sounds great, I will check it out. Thank you. I would also consider submitting a PR for bugs/enhancements in the future.

**Comment by HakanL** [comment]
I welcome all PRs as well, but either way is fine. I use this in a commercial product as well, so it's good to get these things fixed. Initially I copied the main code from another project way back, there were definitely some errors/assumptions that has been fixed.

**Comment by JoeSchulte** [comment]
In your [Obsolete] attribute you can put a comment to direct people to the enum to use instead. That comment will show up in your warnings then.
[Obsolete("Use Output instead of DMX")], it would have saved me a couple of minutes looking it up.

**Comment by HakanL** [comment]
That's a great suggestion, pushed!
