### ISSUE TITLE
Doesn't receive required Poll packet from self

### ISSUE THREAD

**Issue by JoeSchulte** [HakanL/Haukcode.ArtNet#8]
From the spec: **The Controller that broadcasts an ArtPoll should also reply to its own message (by unicast) with an ArtPollReply.**
I'm not sure if other packet types need to be heard from self but at least the Poll packet should not be filtered out.
These packets are currently filtered out with the line:
if (!base.LocalEndPoint.Equals(endPoint) && artNetReceiveData.Valid)

**Comment by HakanL** [comment]
Makes sense, fix pushed. You should see it in NuGet version 1.3.13 and later

**Comment by JoeSchulte** [comment]
I think you may have broken something here; I don't seem to receive any packets now.

**Comment by HakanL** [comment]
Hmm, I get packets here. The change is in this line, do you see anything wrong, it looks correct to me?
https://github.com/HakanL/Haukcode.ArtNet/blob/master/ArtNet/ArtNet/Sockets/ArtNetSocket.cs#L117

**Comment by JoeSchulte** [comment]
I guess I am receiving packets, but the packet type doesn't seem to be set. It reports as ArtNetUnknownPacket.

                                                case ArtNetOpCodes.Poll:
                                                            if (e.Packet is ArtPollPacket artNetPollPacket)

**Comment by JoeSchulte** [comment]
Is the problem in the Create function, maybe the cast to the OpCode? Does that need to manually combine the 2 bytes correctly?

switch ((ArtNetOpCodes)data.OpCode)

**Comment by HakanL** [comment]
Ah, yes, you're correct. The sample didn't use this piece of code so I didn't see the issue. I just pushed a fixed, thanks for finding it!

**Comment by JoeSchulte** [comment]
OK, last thing I see is that you probably need to let the PollReply packet through too on the local address so you can hear your own reply.

**Comment by HakanL** [comment]
You're probably right, my code isn't using the Poll/Reply parts locally so I haven't looked into what makes sense, but I've pushed the fix for that as well.

**Comment by JoeSchulte** [comment]
That seems to work, thanks for the changes.

**Comment by HakanL** [comment]
Excellent, thanks for reporting and testing!
