### ISSUE TITLE
Implement correct semantic versioning

### ISSUE THREAD

**Issue by CDTR-MattConroy** [HakanL/Haukcode.ArtNet#9]
Upgrading from 1.3.16 to 1.3.20-23 causes breaking changes with the removal of ArtNetSocket.

There is also no examples or samples of what to use instead. I presume ArtNetClient, but they not are directly comparable.

**Comment by HakanL** [comment]
Sorry about that, I'm in the middle of rewriting it to use better performance practices and that will cause breaking changes. I have bumped the Nuget version to 2.0 to indicate breaking changes and deprecated the incorrect versions. The last compatible version is 1.3.16.

**Comment by HakanL** [comment]
I've added a small example now as well if you want to use the new API. The main difference is that writing packets (and soon reading) will use memory spans instead of allocating a bunch of buffers.
